name: Compilador Pochi OS APK

on:
  push:
    branches: [ "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar herramienta de compilacion web a APK
        run: |
          npm install -g nativefier

      - name: Compilar Pochi OS a APK
        run: |
          nativefier --name "PochiOS" . ./output_app --ignore-certificate
          ls -la ./output_app

      - name: Subir APK generado
        uses: actions/upload-artifact@v4
        with:
          name: PochiOS-APK
          path: output_app/
          
